server:
  port: 8206

mybatis-plus:
  type-enums-package: com.atclq.ssyx.enums # 表明在实体类中有实体类型的属性，需要指定枚举类所在包路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shequ-user?characterEncoding=utf-8&useSSL=false
    username: root
    password: root

  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 1800000
    password:
    lettuce:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

wx:
  open:
    # 小程序微信公众平台appId
    app_id: wx63af61a0b5e2e266
    # 小程序微信公众平台api秘钥
    app_secret: 98082356e67fe62eb7aee2f0a6888265